### ISSUE TITLE
PHP 7-dev Error

### ISSUE THREAD

**Issue by avindra** [bobthecow/psysh#185]
This may a bit early, but better sooner than later. When trying to start psysh in PHP7-dev, you see:

```
Fatal error: "Scalar\String" cannot be used as a type declaration in phar:///app/php/bin/psysh/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php on line 86
```

**Comment by GrahamCampbell** [comment]
This has already been fixed by php-parser. One sec...

**Comment by avindra** [comment]
Thanks for looking into it... unfortunately, I downloaded the new release of psysh and am still seeing the error:

```Fatal error: "Scalar\String" cannot be used as a type declaration in phar:///app/php/bin/psysh/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php on line 86```

**Comment by GrahamCampbell** [comment]
@avindra Yes. It's not fixed in that release. Fixing php 7 is relatively low priority, and required us to rename classes, so the fix will only be included in 0.5.0, whenever that gets released.

**Comment by bobthecow** [comment]
@avindra In the meantime, you can install the dev version to get the PHP 7 fixes. Either add it as a composer dependency, or if you're using the prebuilt phar, you can check out the repo and build a new phar version. Let me know if you need more details on either of those :)

**Comment by avindra** [comment]
Hm, I just tried compiling the phar with ```/app/psysh/bin# ./compile```. It put out the phar file, but when I try to use it I see :

```./psysh.phar

Fatal error: "string" cannot be used as a class name in phar:///app/psysh/bin/psysh.phar/src/Psy/CodeCleaner/MagicConstantsPass.php on line 19```

Here is the php version:

```
php -v
PHP 7.0.0-dev (cli) (built: Mar 26 2015 19:19:40)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies
```
I am on the master branch.

**Comment by GrahamCampbell** [comment]
You need the develop branch. :)

**Comment by avindra** [comment]
D'oh! Checking out develop works:

```
:/app/psysh/bin# ./psysh.phar
Psy Shell v0.4.4 (PHP 7.0.0-dev — cli) by Justin Hileman
>>> 2 + 2;
=> 4
>>>
```

Thanks guys.

**Comment by GrahamCampbell** [comment]
Oops - we forgot to update the version constant on the develop ranch, lol.

**Comment by bobthecow** [comment]
@GrahamCampbell Heh :)

**Comment by bobthecow** [comment]
Everything is passing in PHP-7 in the develop branch. Are there any other known issues?

**Comment by GrahamCampbell** [comment]
> Are there any other known issues?

D'no. I've never actually used php 7 before, lol.

**Comment by bobthecow** [comment]
Heh :)

**Comment by staabm** [comment]
see https://github.com/php/php-src/blob/master/UPGRADING for a list of changes in php7

**Comment by bobthecow** [comment]
I'm familiar with the list of changes. I was just wondering if anyone had run into any other issues with PsySH in PHP 7. It *seems* to be working now, per the tests, but I haven't bothered setting up PHP 7 to try it out myself yet :)
