### ISSUE TITLE
List assignment doesn't work with array elements

### ISSUE THREAD

**Issue by utikeev** [bobthecow/psysh#521]
Whenever you try to make a list assignment to elements of an array, you get the following error:
```php
Psy Shell v0.9.7 (PHP 7.2.9-1+ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> $a = [];
=> []
>>> [$a[0], $a[1]] = [9, 8]
PHP Parse error: Assignments can only happen to writable values on line 1
```

Though this code works fine via PHP:
```
$ cat test.php
   1   │ <?php
   2   │ $a = [];
   3   │ [$a[0], $a[1]] = [9, 8];
   4   │ var_dump($a)
   5   │ ?>
$ php test.php 
/home/utikeev/What/test.php:4:
array(2) {
  [0] =>
  int(9)
  [1] =>
  int(8)
}
```

**Comment by utikeev** [comment]
I looked it up and it seems that you don't work through this situation in `CodeCleaner/ListPass.php`:
`$value = ($item instanceof ArrayItem) ? $item->value : $item;`

Although this piece of code is parsed by PhpParser to:
```
var: Expr_Array(
                items: array(
                    0: Expr_ArrayItem(
                        key: null
                        value: Expr_ArrayDimFetch(
                            var: Expr_Variable(
                                name: a
                            )
                            dim: Scalar_LNumber(
                                value: 0
                            )
                        )
                        byRef: false
                    )
                    1: Expr_ArrayItem(
                        key: null
                        value: Expr_ArrayDimFetch(
                            var: Expr_Variable(
                                name: a
                            )
                            dim: Scalar_LNumber(
                                value: 1
                            )
                        )
                        byRef: false
                    )
                )
            )
```

**Comment by bobthecow** [comment]
Thanks for reporting this. It's been fixed in 33caffea6c08f64868e1c4acb6b0d10813846066 and will go out with the next release :)

**Comment by utikeev** [comment]
This still won't work with deeper entities, I think. Consider some of these cases.
```php
$a = [];
[$a[0][0][0], $a[0][0][1]] = [9, 8];
$b = new \stdClass;
[$b->x[0], $b->y[1]] = [9, 8];
$c = [];
$c[0] = new \stdClass;
[$c[0]->x[0], $c[0]->y[1]] = [9, 8];
```

**Comment by bobthecow** [comment]
ohhh, interesting:

```
[
  PhpParser\Node\Stmt\Expression {#2335
    type: "Stmt_Expression",
    attributes: [
      "startLine" => 1,
      "endLine" => 1,
    ],
    expr: PhpParser\Node\Expr\ArrayDimFetch {#2868
      type: "Expr_ArrayDimFetch",
      attributes: [
        "startLine" => 1,
        "endLine" => 1,
      ],
      var: PhpParser\Node\Expr\ArrayDimFetch {#2866
        type: "Expr_ArrayDimFetch",
        attributes: [
          "startLine" => 1,
          "endLine" => 1,
        ],
        var: PhpParser\Node\Expr\ArrayDimFetch {#2864
          type: "Expr_ArrayDimFetch",
          attributes: [
            "startLine" => 1,
            "endLine" => 1,
          ],
          var: PhpParser\Node\Expr\Variable {#2862
            type: "Expr_Variable",
            attributes: [
              "startLine" => 1,
              "endLine" => 1,
            ],
            name: "a",
          },
```

I meant to make that "if you're asking about an array index or a property, just accept it and move on, but I figured the `->var` reference would be on the ArrayDimFetch or PropertyFetch, not nested like that. I'll fix the fix when I get a minute :)

**Comment by bobthecow** [comment]
ugh. one more:

```
function x() {
  static $y; 
  if (!$y) $y = new StdClass;
  return $y;
}
[x()->a, x()->b] = [1,2];
x();
```

**Comment by bobthecow** [comment]
Okay. I think that's probably it?

**Comment by jhdxr** [comment]
I hope the latest release (0.9.9) contains this fix, otherwise I may have to build the phar on my windows.

here is a simple code while still can reproduce this issue
```
[$a, $b, [$c]] = [1,2,[3]];
```

env: Psy Shell v0.9.9 (PHP 7.2.14 — cli) on windows 10, and I confirm the same issue exists on linux as well.
